-- MySQL Script generated by MySQL Workbench
-- Mon Dec  6 23:35:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema php_avance
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema php_avance
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `php_avance` DEFAULT CHARACTER SET utf8 ;
USE `php_avance` ;

-- -----------------------------------------------------
-- Table `php_avance`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_avance`.`ticket` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `state` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_avance`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_avance`.`comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `php_avance`.`ticket_has_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `php_avance`.`ticket_has_comment` (
  `ticket_id` INT UNSIGNED NOT NULL,
  `comment_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ticket_id`, `comment_id`),
  INDEX `fk_ticket_has_comment_comment1_idx` (`comment_id` ASC),
  INDEX `fk_ticket_has_comment_ticket_idx` (`ticket_id` ASC),
  CONSTRAINT `fk_ticket_has_comment_ticket`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `php_avance`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_has_comment_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `php_avance`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
